# Generated by Django 6.0.4 on 2026-04-29 07:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0004_alter_user_auth0_user_id_and_more"),
        ("devices", "0002_device_created_at_device_updated_at_deviceassignment"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="deviceassignment",
            name="unique_device_assignment_per_tenant",
        ),
        migrations.AddConstraint(
            model_name="deviceassignment",
            constraint=models.UniqueConstraint(
                fields=("device", "tenant"),
                name="unique_active_device_assignment_per_tenant",
            ),
        ),
    ]
