# Generated by Django 6.0.4 on 2026-04-12 19:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_seed_default_tenant"),
    ]

    operations = [
        migrations.AddField(
            model_name="doctorprofile",
            name="surname",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="patientprofile",
            name="surname",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
    ]
