# Generated by Django 6.0.4 on 2026-04-13 10:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_doctorprofile_surname_patientprofile_surname"),
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="auth0_user_id",
            field=models.CharField(max_length=255),
        ),
        migrations.AddConstraint(
            model_name="user",
            constraint=models.UniqueConstraint(
                fields=("auth0_user_id", "tenant", "role"),
                name="unique_user_membership_per_tenant_role",
            ),
        ),
    ]
