# Generated by Django 6.0.4 on 2026-04-30 10:59

import django.db.models.deletion
import measurements.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0004_alter_user_auth0_user_id_and_more"),
        ("devices", "0004_deviceassignment_valid_window_and_indexes"),
        ("measurements", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MeasurementSession",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=measurements.models.generate_ulid_str,
                        editable=False,
                        max_length=26,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("started_at", models.DateTimeField()),
                ("stopped_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "device_assignment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="measurement_sessions",
                        to="devices.deviceassignment",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="measurement_sessions",
                        to="accounts.tenant",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["tenant", "device_assignment", "started_at"],
                        name="ms_assignment_hist_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("stopped_at__isnull", True)),
                        fields=("tenant", "device_assignment"),
                        name="uniq_active_session_per_assign",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("stopped_at__isnull", True),
                            ("stopped_at__gt", models.F("started_at")),
                            _connector="OR",
                        ),
                        name="ms_stopped_after_started",
                    ),
                ],
            },
        ),
    ]
