# Generated by Django 6.0.4 on 2026-05-06 08:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("measurements", "0003_measurement_to_session"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="measurement",
            name="hrv",
        ),
        migrations.AddField(
            model_name="measurement",
            name="rmssd",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="measurement",
            name="sdnn",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="measurement",
            name="heart_rate",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name="measurement",
            constraint=models.UniqueConstraint(
                fields=("tenant", "measurement_session", "timestamp"),
                name="uniq_measurement_per_session_ts",
            ),
        ),
    ]
